wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 80:80
  volumes:
    - ./www:/var/www/html/
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: sdc
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 81:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: sdc
php:
  build: ./php/.