sdc_wp:
  image: gravityrail/wordpress
  links:
    - sdc_db:mysql
  ports:
    - 80:80
  volumes:
    - ./www:/var/www/html/
sdc_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
sdc_phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - sdc_db:mysql
  ports:
    - 81:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: root
